# Generated by Django 3.1.3 on 2020-11-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('type', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1500)),
                ('votes_pos', models.IntegerField()),
                ('votes_neg', models.IntegerField()),
                ('author_id', models.IntegerField()),
            ],
        ),
    ]
